### ISSUE TITLE
Meetup #17 with Ravi Dhungel | Scaling and performance engineering on distributed systems  

### ISSUE THREAD

**Issue by thapakazi** [DevOps-Kathmandu/CFP#7]
# Event Details

Meetup No : **17**
Proposed date  : **Sunday 4 Oct, 8:30 PM UTC+5:45** :nepal:  
Confirmed date :  _**pending**_

**Meetup:**         https://www.meetup.com/DevOps-Kathmandu/events/.../
**Meetup Link:** https://meet.google.com/...-...-...

 

## Speaker Bio 

**Ravi Dhungel** | Janitor of science, nature and society || Former Major && Pacifist

**Current**: Chief Information Security Officer and Platform Engineering

Mr. Ravi Dhungel is a former major of Nepalese Army with expertise on technology management, cyber security and national security. Mr Dhungel is great mentor of computer science, cyber security, immigration and higher education. He likes to talk about global policies, south-asian politics, Linux/computing and also loves to hike over the Himalayas. 

In his own words:  "I have a solid foundation on principles of security, distributed system,software engineering, and secured very large-scale distributed systems (HPC , Hadoop, and telecom systems ~55 millions). I have worked on startup to fortune 500 companies in industry verticals of telecom, software, biomedical, university, healthcare, and a military."

Connect him on: https://www.linkedin.com/in/ravidhungel/

## Meetup Description

**Title:**  **_Scaling and performance engineering on distributed systems_** 

**Description:**
In this session Mr. Ravi Dhungel would cover:
- Performance and Scaling
- Vertical scaling versus horizontal scaling
- Systems architecture
- System services
- Software architecture - microservices
- High Performance Computing (HPC)
- Troubleshooting101 of distributed systems 

## Resources
**Curation:**       https://github.com/DevOps-Kathmandu/curation
**Youtube:**       https://www.youtube.com/channel/UChIow3i-WObHKidPD_xwwlA/videos
**Slack:**           http://bit.ly/devops-kathmandu-slack
**Q/A docs:**     http://bit.ly/devops-kathmandu-area.
 
## Actions / Flow
- [x] Confirm date and time with speaker
- [x] Collect speakers { bio, meetup title, description, photo }
- [ ] Media banner with speaker photo
- [ ] Publish to meetup group
- [ ] Shared on media: twitter, facebook groups, slack
- [ ] Update Q/A docs

**Comment by thapakazi** [comment]
Draft prepared: https://www.meetup.com/DevOps-Kathmandu/events/273504862/

**Comment by dwdraju** [comment]
Event published https://www.meetup.com/DevOps-Kathmandu/events/273504862/
Calendar also invite sent to speaker and hosts.
