### ISSUE TITLE
Community All Hands

### ISSUE THREAD

**Issue by dwdraju** [DevOps-Kathmandu/CFP#8]
# Event Details

**Meetup No** : 18
**Proposed date**  : 11th October, 5PM-6PM UTC+5:45 
**Confirmed date** :  pending

**Meetup:**         https://www.meetup.com/DevOps-Kathmandu/events/.../
**Meetup Link:** https://meet.google.com/...-...-...

**Title:**  _Community All Hands_ 
---
## Meetup Description
Agendas:
1. Retrospective session
2. Planning Discussion on SIG over CNCF landscape
// TODO

**Comment by thapakazi** [comment]
Closing this; looks like we forgot to cleanup :sweat_smile:
